print('begins...')
x = 10
print(x)             # sorun yok!
#print(y)             # exception olu≈üur!
